#!/bin/env sh

# The devenv function

devenv() {
	local devenv=${u_prefix}/devenv.sh

	local path=${u_prefix}/bin

	local cmake_prefix_path=${PREFIX}
	local pkg_config_libdir=${PREFIX}
	local pkg_config_path=

	local infopath=${u_prefix}/share/info
	local manpath=${u_prefix}/share/man

	if [ ${u_prefix} != ${u_programs_prefix} ]; then
		path="${path}:${u_programs_prefix}/bin"

		cmake_prefix_path="${cmake_prefix_path};${PROGRAMS_PREFIX}"
		pkg_config_path=${PROGRAMS_PREFIX}

		infopath="${infopath}:${u_programs_prefix}/share/info"
		manpath="${manpath}:${u_programs_prefix}/share/man"
	fi

	local _pkg_config_libdir
	local _pkg_config_path

	local save_IFS=${IFS}
	IFS=';'

	local dir

	for dir in ${pkg_config_libdir}; do
		if [ -z "${_pkg_config_libdir}" ]; then
			_pkg_config_libdir="${dir}/lib/pkgconfig;${dir}/share/pkgconfig"
		else
			_pkg_config_libdir="${_pkg_config_libdir};${dir}/lib/pkgconfig;${dir}/share/pkgconfig"
		fi
	done

	for dir in ${pkg_config_path}; do
		if [ -z "${_pkg_config_path}" ]; then
			_pkg_config_path="${dir}/lib/pkgconfig;${dir}/share/pkgconfig"
		else
			_pkg_config_path="${_pkg_config_path};${dir}/lib/pkgconfig;${dir}/share/pkgconfig"
		fi
	done

	IFS=${save_IFS}

	cat <<-EOF >${devenv}
		# devenv.sh
		#
		# generated by ${self}

		export PATH=${path}:\${PATH}

		export CMAKE_PREFIX_PATH="${cmake_prefix_path}"
		export PKG_CONFIG_LIBDIR="${_pkg_config_libdir}"
		export PKG_CONFIG_PATH="${_pkg_config_path}"

		if test \${INFOPATH+y}
		then
			INFOPATH=${infopath}:\${INFOPATH}
		else
			export INFOPATH=${infopath}
		fi

		if test \${MANPATH+y}
		then
			MANPATH=${manpath}:\${MANPATH}
		else
			export MANPATH=${manpath}
		fi
	EOF

	chmod +x ${devenv}
}
